name: Python Application

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest numpy pygame
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    
    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          python3-dev \
          libsdl2-dev \
          libsdl2-image-dev \
          libsdl2-mixer-dev \
          libsdl2-ttf-dev \
          libportmidi-dev \
          ffmpeg \
          libavcodec-dev \
          libavformat-dev \
          libswscale-dev
    
    - name: Test with pytest
      run: |
        pytest test_conways_game_of_life.py -v

    - name: Upload test results
      uses: actions/upload-artifact@v2
      with:
        name: test-results
        path: .pytest_cache